name: Build sysext and confext

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup-mkosi
        uses: systemd/mkosi@v24.3

      - run: |
          mkosi build
