name: Build sysext and confext

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        image:
          - ghcr.io/ublue-os/bazzite
          - ghcr.io/ublue-os/bluefin

    steps:
      - name: Setup BTRFS partition
        run: |
          set -xe
          BTRFS_FILE=/mybtrfs.img
          # Dowload btrfs-progs
          sudo apt-get install -y btrfs-progs
          # Create partition
          sudo truncate -s $(findmnt --target . --bytes  --df --json | jq -r '.filesystems[0].avail * 0.8 | round') "$BTRFS_FILE"
          sudo mkfs.btrfs -r "$GITHUB_WORKSPACE" "$BTRFS_FILE"
          pushd /
          sudo systemd-mount "$BTRFS_FILE" "$GITHUB_WORKSPACE" --options=compress-force=zstd:1
          popd

      - uses: actions/checkout@v4

      - uses: extractions/setup-just@v2

      - name: setup-mkosi
        uses: systemd/mkosi@10fdbdf3d9db6c3d5e452f1f404d1c6438425c0b

      - name: Maximize build space
        uses: ublue-os/remove-unwanted-software@v7

      - name: Build sysext for ${{ matrix.image }}
        id: build
        run: |
          DEBUG=1 just prepare-overlay-tar ${{ matrix.image }}
          mkosi --force build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.image }}_${{ steps.build.outputs.format }}.raw
          path: mkosi.output/*.raw
          retention-days: 1
