name: Build sysext and confext

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: extractions/setup-just@v2

      - name: setup-mkosi
        uses: systemd/mkosi@10fdbdf3d9db6c3d5e452f1f404d1c6438425c0b

      - run: |
          just build ghcr.io/ublue-os/bazzite 10-example

      - uses: actions/upload-artifact@v4
        with:
          name: 10-example_sysext.raw
          path: mkosi.output/10-example_sysext.raw
          retention-days: 1

      - uses: actions/upload-artifact@v4
        with:
          name: 10-example_confext.raw
          path: mkosi.output/10-example_confext.raw
          retention-days: 1
