name: Build sysext and confext

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        image:
          - ghcr.io/ublue-os/bazzite:41
          - ghcr.io/ublue-os/bluefin:41

    permissions:
      contents: write

    steps:
      - name: Setup BTRFS partition
        run: |
          set -xe
          BTRFS_FILE=/mybtrfs.img
          # Dowload btrfs-progs
          sudo apt-get install -y btrfs-progs
          # Create partition
          sudo truncate -s $(findmnt --target . --bytes  --df --json | jq -r '.filesystems[0].avail * 0.8 | round') "$BTRFS_FILE"
          sudo mkfs.btrfs -r "$GITHUB_WORKSPACE" "$BTRFS_FILE"
          pushd /
          sudo systemd-mount "$BTRFS_FILE" "$GITHUB_WORKSPACE" --options=compress-force=zstd:1
          popd

      - uses: actions/checkout@v4

      - uses: extractions/setup-just@v2

      - name: setup-mkosi
        uses: systemd/mkosi@38cbf1e4845ca3bbd4195867cf22032b1bbd32d5

      - name: Maximize build space
        uses: ublue-os/remove-unwanted-software@v7

      - name: Build sysext for ${{ matrix.image }}
        id: build
        run: |
          DEBUG=1 just prepare-overlay-tar ${{ matrix.image }}
          sudo mkosi --debug --force build

      - name: Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -xe

          # Create a release for the current tag, based in the value of OSTREE_VERSION in mkosi.basetree/usr/lib/os-release
          OSTREE_VERSION=$(cat mkosi.basetree/usr/lib/os-release | grep ^OSTREE_VERSION | cut -d= -f2)
          RELEASE_NAME=sysext-kitchen-${{ matrix.image }}-${OSTREE_VERSION}-${{ github.sha }}
          RELEASE_TAG=$(echo "${{ matrix.image }}" | rev | cut -d'/' -f1 | rev | cut -d':' -f1)-${OSTREE_VERSION}

          gh release delete $RELEASE_TAG --yes || true
          gh release create $RELEASE_TAG --title $RELEASE_NAME --notes 'System extensions for `${{ matrix.image }}`'
          (cd mkosi.output && gh release upload $RELEASE_TAG *.raw)
