name: Build sysext and confext

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: extractions/setup-just@v2

      - run: sudo apt update -y && sudo apt install -y systemd-repart

      - name: setup-mkosi
        uses: systemd/mkosi@v24.3

      - run: |
          just build ghcr.io/ublue-os/bazzite 10-example
