name: Build sysext and confext

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        image:
          - ghcr.io/ublue-os/bazzite:41
          - ghcr.io/ublue-os/bluefin:41

    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup mkosi workspace
        uses: ./.github/workflows/mkosi_setup

      - uses: extractions/setup-just@v2

      - name: Maximize build space
        uses: ublue-os/remove-unwanted-software@v7

      - name: Build sysext for ${{ matrix.image }}
        id: build
        run: |
          DEBUG=1 just prepare-overlay-tar ${{ matrix.image }}
          sudo mkosi \
            --debug \
            --force \
            --dependency=dx-sysext,dx-confext \
            build

      - name: Upload sysext
        uses: ./.github/workflows/upload_sysext/action.yml
        with:
          working-directory: mkosi.output
          basetree: ${{ github.workspace }}/mkosi.basetree
          raw-files: |
            dx*.raw
